# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    #wconfig.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder ".", "/var/www/html"
    web.vm.network "private_network", ip: "192.168.1.2"
    #web.vm.network "public_network", ip: "192.168.1.2"
    web.vm.provision "shell", inline: <<-SHELL
    echo "webserver" > /etc/hostname
      hostname -b webserver
      sudo apt-get update
      sudo apt-get upgrade
      sudo apt install -y php libapache2-mod-php
      sudo systemctl restart apache2

    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.network "private_network", ip: "192.168.1.5"
    #db.vm.network "public_network", ip: "192.168.1.5"
    db.vm.provision "shell", inline: <<-SHELL
    echo "dbserver" > /etc/hostname
        hostname -b dbserver

      sudo apt-get update
      sudo apt-get upgrade
      sudo apt-get install -y postgresql postgresql-contrib
    

      SHELL
  end

  config.vm.define "gateway" do |gateway|
    gateway.vm.box = "ubuntu/bionic64"
    gateway.vm.network "private_network", ip: "192.168.1.30"
   #gateway.vm.network "public_network", ip: "192.168.1.31"
    gateway.vm.provision "shell", inline: <<-SHELL
    echo "gateway" > /etc/hostname
      hostname -b gateway

      sudo apt-get update
      sudo apt-get upgrade
      #sudo apt install -y nodejs npm
    

    SHELL
  end


  

end
